### ISSUE TITLE
Remove references to Eclipse IDE & other content not relevant to Jakarta EE 

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#103]
In top-level navigation More dropdown menu, remove Eclipse IDE column:
Eclipse IDE
- Download
- Documentation
- Getting Started / Support
- How to Contribute
- IDE and Tools
- Newcomer Forum

Keep the Community and Participate dropdown:
Community
- Marketplace
- Events
- Planet Eclipse
- Newsletter
- Videos
- Blogs

Participate
- Report a Bug
- Forums
- Mailing Lists
- Wiki
- IRC
- Research

**Comment by chrisguindon** [comment]
I created an issue to our Hugo solstice theme. This is something that we need to fix in the theme layer.

For more information, please view [Add option to alter the More menu #15](https://github.com/EclipseFdn/hugo-solstice-theme/issues/15)

**Comment by chrisguindon** [comment]
A fix was made to the theme layer. We should be able to address this issue now.

**Comment by chrisguindon** [comment]
After a discussion with @ThabangMash, it was decided to remove the more dropdown for now.

This is now live! Closing this bug!
