### ISSUE TITLE
Create a Resources drop down menu with links to pages for surveys, videos, specs, etc.

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#108]
Create Resources drop down similar to iot.eclipse.org
Link to pages for:
- Surveys
** 2018 Developer [Survey](https://jakarta.ee/documents/insights/2018-jakarta-ee-developer-survey.pdf)
- Infographics
** https://jakarta.ee/documents/insights/2018-jakarta-ee-survey-infographic.pdf
- Videos
** Add videos from Jakarta EE talks, sessions, community events (including Jakarta Tech Talks)
https://www.youtube.com/playlist?list=PLy7t4z5SYNaT-6PRtijB8XZQJ7jq020CO
https://www.youtube.com/watch?v=rZ3zx2UAG9c&feature=youtu.be
- Specification Process
-- Talks/presentations on Spec Process
https://docs.google.com/presentation/d/1Gf8awQxHs1J13LG9dAcGc_q-YC4EtHeIc5Gjm54eDAA/edit#slide=id.g42b8515be3_0_0
https://www.eclipsecon.org/europe2018/sessions/directors-pick-introducing-eclipse-foundation-specification-process
- Newsletter Archives
-- https://jakarta.ee/newsletter/ 
- Meeting Minutes
-- https://jakarta.ee/meeting_minutes/
- Future:
** White Papers 
** Case Studies

**Comment by jgallimore** [comment]
Adding the page itself looks to be fairly straightforward - we'd just need to draft up the content for it. Here's a screenshot of a resources page I hacked up using the YouTube video @ThabangMash referenced:

![image](https://user-images.githubusercontent.com/548624/45156139-2dd6c380-b1d5-11e8-9f06-dab09f233a64.png)

**Comment by ericpoirier** [comment]
Hi Thabang,

Here is a screenshot of the Resources page containing the different sections mentioned in your first comment.

As we agreed, all the sections will be located on the Resources page until there is enough content to create a separate page.

![screenshot_2019-02-27 resources the eclipse foundation](https://user-images.githubusercontent.com/623165/53518289-b9ebe880-3a9e-11e9-9d16-fb09417702b5.png)

Please note that once I'm done with all the pull requests for the Jakarta EE website, the events will no longer be in the footer. This screenshot is just to show you the content part of the page.

Let me know if you have any comments.

Thanks.

**Comment by ThabangMash** [comment]
Thanks Eric. Looks good. On the drop-down, there is a typo, it should be
"Infographics"

**Comment by ericpoirier** [comment]
Hi Thabang,

I fixed the typo in my pull request. Let me know if there's anything else. Otherwise I'll wait for your +1 to go live with this.

Thanks.

**Comment by chrisguindon** [comment]
I reviewed your pull request with @ThabangMash and I approved your pull request!

The changes should go live any minute now!

Thank you!
