### ISSUE TITLE
Add embedded poll / survey (using Twitter, SurveyMonkey, or other tech) to gather community feedback.

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#109]
**This is a placeholder, more details to come**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisguindon** [comment]
Assigning this request to Stephanie.

**Comment by ThabangMash** [comment]
This issue has not been elaborated on, so can be closed.

**Comment by chrisguindon** [comment]
@ThabangMash +1
