### ISSUE TITLE
Move Member logos from main page to https://jakarta.ee/members/

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#111]
**This is a placeholder, more details to come**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgallimore** [comment]
The members page could look like this, with just a straight move of the HTML.

![snip20180906_1](https://user-images.githubusercontent.com/548624/45154973-4a70fc80-b1d1-11e8-9295-31e86adf8a93.png)

**Comment by jgallimore** [comment]
This is just for discussion, but if this looks good I created the image above by changing the code, so I'd be more than happy to push a PR for this. My change was a straight copy of the html into the markdown file; I did not convert the HTML itself to markdown.

![snip20180906_2](https://user-images.githubusercontent.com/548624/45155106-c10dfa00-b1d1-11e8-9ccb-a692aa8b1a53.png)

**Comment by chrisguindon** [comment]
@jgallimore I think this is a great start!

Here's a few other ideas:
-  Display the members on a separate page similar to eclipse.org (https://www.eclipse.org/membership/ & https://www.eclipse.org/membership/exploreMembership.php)

- Based of your latest mock up, we could also consider moving the list of members after "Who should participate" text.

**Comment by ericpoirier** [comment]
Hi Thabang,

Here are some screen shots of the changes I've been working on for the Home page, membership page and members page.

![screenshot_2019-02-26 jakarta ee software cloud native the eclipse foundation](https://user-images.githubusercontent.com/623165/53440034-8f802980-39d1-11e9-9001-b8d1380a7a7c.png)
![screenshot_2019-02-26 shape the future of jakarta ee the eclipse foundation](https://user-images.githubusercontent.com/623165/53440038-91e28380-39d1-11e9-9382-9bcbd4eed1b0.png)
![screenshot_2019-02-26 shape the future of jakarta ee the eclipse foundation 1](https://user-images.githubusercontent.com/623165/53440041-94dd7400-39d1-11e9-9906-e6b21cf22ac7.png)

Let me know what you think and if you'd like to make some changes.

Thanks.

**Comment by chrisguindon** [comment]
The change was committed. This should go live in a few minutes!

Thank you @ericpoirier!
