### ISSUE TITLE
Updates to Jakarta.ee home page, including Replacing Member logos area with Events

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#112]
**Jumbotron Text**

- Same text: Jakarta EE
- **Updated text:** The Home of Open Source Cloud Native Java 
- Same text: Powered by participation, Jakarta EE is focused on enabling community-driven collaboration and open innovation for the cloud.

**Buttons**

- “Why the Jakarta EE Working Group?” (new button text) → no change to link
- “Projects” (new button) → https://jakarta.ee/projects/ (under construction)
- “Stay Connected” → no change to link
- “Join Us” (new button) → new link: https://jakarta.ee/membership/ 

**Member logos**

- Remove from homepage

**Events**

- Move section up to immediately underneath the jumbotron
- Section tagline
-- “Join the global Jakarta EE community at these upcoming events!”
- Event submission form tagline
-- “Want to add your event? Please complete and submit our event form”

**Announcements and Community News**

- Place Announcements and Community News side by side like eclipse.org 
- Announcements 
-- Most recent 5 
- Community News
-- Most recent 5

**Sign up to our Newsletter**

- Move to the footer (appears on every page)

**Comment by jgallimore** [comment]
The events are currently in the footer, which is added to every page - for example, this is the bottom of the members page:

![image](https://user-images.githubusercontent.com/548624/45155232-311c8000-b1d2-11e8-9703-73407ade9b49.png)

Would we still want to keep the `Events` and `Submit to Events` on the footer on every page?

**Comment by ericpoirier** [comment]
Here are some screenshots of what I'm currently working on for the various changes on the Jakarta EE website:

![screenshot_2019-02-26 jakarta ee software cloud native the eclipse foundation](https://user-images.githubusercontent.com/623165/53445171-f60b4480-39dd-11e9-9ced-7d4fc02c2d29.png)

![screenshot_2019-02-26 shape the future of jakarta ee the eclipse foundation](https://user-images.githubusercontent.com/623165/53445176-f86d9e80-39dd-11e9-884c-8d67bac579d6.png)

![screenshot_2019-02-26 shape the future of jakarta ee the eclipse foundation 1](https://user-images.githubusercontent.com/623165/53445198-01f70680-39de-11e9-8755-6a9f2e50ebd0.png)

**Comment by ThabangMash** [comment]
Looking good, Eric!

For the jumbotron text, can you change to
“Open Source Cloud Native Java”?

Can you please make the Submit Event button the same width and colour as the View More Events button?

On Membership page:
- delete second heading “Jakarta EE is the home of open, cloud native Java innovation.”
- remove italics on all member testimonials
- bold names & titles on all member testimonials 
- delete “We will get back to you within two business days”. Replace with “We will get back to you soon. We look forward to speaking with you!”

Jumbotron text for Membership > Members page: “Our Members” [replaces “Shape the Future of Jakarta EE”]

**Comment by ThabangMash** [comment]
Wow! Great progress Eric!

Exciting times!!!

Tanja

**Comment by ericpoirier** [comment]
Thanks Thabang for the feedback, here are other sets of screenshots based on your comments:

![screenshot_2019-02-27 jakarta ee software cloud native the eclipse foundation](https://user-images.githubusercontent.com/623165/53495246-8cd31200-3a6d-11e9-8b87-0ebba02035c6.png)

![screenshot_2019-02-27 shape the future of jakarta ee the eclipse foundation](https://user-images.githubusercontent.com/623165/53495253-90669900-3a6d-11e9-8c0d-54fa4791e176.png)

![screenshot_2019-02-27 our members the eclipse foundation](https://user-images.githubusercontent.com/623165/53495258-93618980-3a6d-11e9-81ee-ce6edaf23f98.png)

**Comment by ericpoirier** [comment]
Hi Thabang,

Let me know if there are more changes to make here.

I'll wait for your +1 to go live with this.

Thanks.

**Comment by chrisguindon** [comment]
I reviewed this changes with @ThabangMash and approved your pull request!

Thanks for doing this!

**Comment by ThabangMash** [comment]
Thanks Eric and Chris!
