### ISSUE TITLE
Improve the Jakarta EE working group page

### ISSUE THREAD

**Issue by delabassee** [jakartaee/jakartaee.github.io#118]
**Issue**

The [Jakarta EE Working Group page](https://jakarta.ee/about/) could be improved.
For example, I was expecting to find more details on the different Jakarta EE WGs (steering, marketing, etc.) on _or_ from this page (goals, membrs, etc.)!

The "Explore" button is a also bit misleading here as it's not related to Jakarta EE but to Eclipse.

**Comment by chrisguindon** [comment]
We had a discussion about this issue and we decided to remote the Explore Eclipse Working Groups button on this page.

**Comment by chrisguindon** [comment]
Pull request was merged! Closing!
