### ISSUE TITLE
Please Add and Remove the following events

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#119]
**To add:**
JJUG Night Seminar "Jakarta EE, MicroProfile, Payara"
Shinjuku-ku, Tokyo
September 28, 2018
Link: https://jjug.doorkeeper.jp/events/79320

JAX LONDON
London, UK
October 8, 2018
https://jaxlondon.com/

**To Remove:**

Javaday Ecuador
Quito, Ecuador
September 8, 2018

Javazone
Oslo Spektrum, Norway
Sep 12-13, 2018

Day of the Programmer
Jönköping, Sweden
Sept 13 2018

**Comment by chrisguindon** [comment]
@ericpoirier I think this was addressed with #120 ?

**Comment by ericpoirier** [comment]
Yes we can now close this issue.
