### ISSUE TITLE
Please create blog about Java EE TCKs being open source

### ISSUE THREAD

**Issue by cealsair** [jakartaee/jakartaee.github.io#122]
**Is your feature request related to a problem? Please describe.**
Apparently, Java EE TCKs were officially made open source on Oct 14, 2018

**Describe the solution you'd like**
Please create a blog post announcing this.

**Describe alternatives you've considered**

**Additional context**

Thank you, 
Cesar

**Comment by ThabangMash** [comment]
https://blogs.eclipse.org/post/tanja-obradovic/java-ee-tck-now-open-sourced-eclipse-foundation

**Comment by chrisguindon** [comment]
+1 Closing the issue as suggested by @ThabangMash
