### ISSUE TITLE
Publishing Specification Committee Meeting Minutes 

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#123]
Is your feature request related to a problem? Please describe.
This is not a problem, but we need to add 5 new entries for
Minutes from Jakarta EE Specification Committee meeting of August 8
Minutes from Jakarta EE Specification Committee meeting of August 15
Minutes from Jakarta EE Specification Committee meeting of August 22
Minutes from Jakarta EE Specification Committee meeting of August 29
Minutes from Jakarta EE Specification Committee meeting of September 5
Describe the solution you'd like

we need to add them on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Specification Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)
Minutes from Jakarta EE Steering Committee Meeting on June 5.pdf

Describe alternatives you've considered

Additional context
I have attached 4 pdf files. Please let me know if you need anything else from me.
[Spec Committee Meeting Minutes August 15, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2402436/Spec.Committee.Meeting.Minutes.August.15.2018.pdf)
[Spec Committee Meeting Minutes August 22, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2402438/Spec.Committee.Meeting.Minutes.August.22.2018.pdf)
[Spec Committee Meeting Minutes August 29, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2402439/Spec.Committee.Meeting.Minutes.August.29.2018.pdf)
[Spec Committee Meeting Minutes September 5th, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2402440/Spec.Committee.Meeting.Minutes.September.5th.2018.pdf)
[Spec Committee Meeting Minutes August 8, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2402441/Spec.Committee.Meeting.Minutes.August.8.2018.pdf)

**Comment by chrisguindon** [comment]
Done! The change should appear on the website in the next few minutes.
