### ISSUE TITLE
Update FAQ's https://jakarta.ee/about/faq/

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#134]
Existing FAQs are out of date 
e.g. Q: What are we announcing on April 24?

Copy must be updated. Precondition is that approved copy must be provided by Eclipse Foundation Marketing team.

**Comment by ericpoirier** [comment]
Hi Thabang,

Could you let me know what you would like to update on the FAQ page?

Thanks.

**Comment by ThabangMash** [comment]
Hi Eric & Chris,  the updated copy text is here:
https://docs.google.com/document/d/1-ZjjP81SHrgLO_hp2LAQ5JEWKU8tT_drqi6WPphkS6E/edit?ts=5bc740de

**Comment by chrisguindon** [comment]
Done! The changes should go live any moment now!
