### ISSUE TITLE
Add Jakarta EE Flyer to https://jakarta.ee/members/ page

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#14]
Add link to member flyer on https://jakarta.ee/members/
Between key benefits and who should participate sections
Button should read "Download Membership Flyer”
Button should be the same size as "Become a Member" button
Please see flyer attached
[Jakarta EE Flyer US-letter.pdf](https://github.com/jakartaee/jakartaee.github.io/files/1964805/Jakarta.EE.Flyer.US-letter.pdf)

@chrisguindon @ericpoirier

**Comment by chrisguindon** [comment]
Done! Thanks!
