### ISSUE TITLE
Please remove all September events from website

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#141]
<stephanie.swart@eclipse-foundation.org>

**Comment by stephanieswart** [comment]
REMOVE THE FOLLOWING:

Payara Services & Azul Systems Java Ecosystem Seminar at the IOD
London, UK
September 18, 2018

jDays
Gothenburg, Sweden
Sept 25 2018

JJUG Night Seminar "Jakarta EE, MicroProfile, Payara"
Shinjuku-ku, Tokyo
Sept 28 2018

JAX LONDON
London, UK
October 8, 2018

**Comment by ericpoirier** [comment]
Hi Stephanie,

These events have been removed from the production website.
