### ISSUE TITLE
Become a Jakarta EE Author 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakartaee.github.io#142]
- https://microprofile.io/blog/

When you click the bottom it brings potential writer directly to git documentation on how to:

- https://github.com/microprofile/wpsite

Jakarta EE blog could emulate MP blog section.

**Comment by chrisguindon** [comment]
Hi @aeiras,

I will close this issue since we already have one open about creating a blogging platform for Jakarta.EE.

Feel free to post your comment on Issue #105
