### ISSUE TITLE
URGENT: Publishing meeting minutes for Specification Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#160]
Is your feature request related to a problem? Please describe.
This is not a problem, but we need to add 2 new entries for
Minutes from Jakarta EE Specification Committee meeting of October 17
Minutes from Jakarta EE Specification Committee meeting of November 7

Describe the solution you'd like
we need to add them on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Specification Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)
Minutes from Jakarta EE Specification Committee Meeting on June 5.pdf

Describe alternatives you've considered

Additional context
I have attached 2
[Spec Committee Meeting Minutes Oct 17th, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2563418/Spec.Committee.Meeting.Minutes.Oct.17th.2018.pdf)
[Spec Committee Meeting Minutes Nov 7th, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2563419/Spec.Committee.Meeting.Minutes.Nov.7th.2018.pdf)

**Comment by TanjaObradovic** [comment]
please upload these 2 files
[Spec Committee Meeting Minutes Oct 17th, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2563441/Spec.Committee.Meeting.Minutes.Oct.17th.2018.pdf)
[Spec Committee Meeting Minutes Nov 7th, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2563442/Spec.Committee.Meeting.Minutes.Nov.7th.2018.pdf)

**Comment by chrisguindon** [comment]
Done!
