### ISSUE TITLE
Please update Jakarta EE Flyer

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#168]
Old flyer on https://jakarta.ee/members/:
https://jakarta.ee/documents/membership/jakarta-ee-membership-flyer.pdf

New flyer attached: 
https://drive.google.com/drive/u/0/folders/1GAmZ9zkTrrKwb4VNwxI3wLZjA3SuzFVz
[Jakarta_Flyer_A4_october2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2699521/Jakarta_Flyer_A4_october2018.pdf)

**Comment by chrisguindon** [comment]
Committed!
