### ISSUE TITLE
Update Jakarta EE FAQs - GlassFish Q&A

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#176]
Q:  What’s going to be in the next release of GlassFish, and when will it get launched?
A: As part of the move to Eclipse, GlassFish is now Eclipse GlassFish. There are going to be two releases of Eclipse GlassFish:
1.  On January 29, 2019, the community will release an Eclipse GlassFish 5.1 which is certified as Java EE 8 compatible. This will also be the first release of all of the projects being moved to the Eclipse Foundation, and as such will be a significant event in the on-boarding of the Java EE 8 technologies into the Eclipse community.
2. Later in 2019, the community will release an Eclipse GlassFish 5.2 which is certified as Jakarta EE 8 compatible. 

https://docs.google.com/document/d/1-ZjjP81SHrgLO_hp2LAQ5JEWKU8tT_drqi6WPphkS6E/edit

**Comment by ericpoirier** [comment]
Hi Thabang,

I forgot to close this issue but this was added to the FAQ page earlier this week.
