### ISSUE TITLE
Jakarta EE News archives are non-existant

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#179]
When I click "View-All' at the bottom of each news section, it only displays 10 news articles without the ability to look at the entire archive:
https://jakarta.ee/news/

Can we fix? 

Stephanie Swart <stephanie.swart@eclipse-foundation.org>

**Comment by ericpoirier** [comment]
Also, I'm noticing that the View all link for Announcements and Community News is going to that same page (https://jakarta.ee/news/). Should it be a different page for each types of news?

**Comment by stephanieswart** [comment]
I think it should be different news streams

**Comment by ericpoirier** [comment]
I merged a patch that created separate pages for Announcements and Community News. They are still showing 10 items each. This is something that will be fixed after there is a new release for the Eclipse Foundation Hugo theme.

**Comment by chrisguindon** [comment]
I created a pull request to deploy an update to the theme:
https://github.com/jakartaee/jakartaee.github.io/pull/211

**Comment by chrisguindon** [comment]
Pagination should appear on the website shortly!

Closing this bug!
