### ISSUE TITLE
Please add to jakarta announcements

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#183]
Jakartablogs.ee is Live! PS: Bloggers, We Need You!
https://blogs.eclipse.org/post/thabang-mashologu/jakartablogsee-live-ps-bloggers-we-need-you

Eclipse releases GlassFish 5.1 for Java EE 8
https://www.infoworld.com/article/3336448/java/eclipse-releases-glassfish-51-for-java-ee-8.html

**Comment by ericpoirier** [comment]
Hi Stephanie,

These announcements are now on the production website.
