### ISSUE TITLE
Please add to community news

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#186]
https://blogs.oracle.com/theaquarium/jakarta-ee-milestone-eclipse-glassfish-51-is-java-ee-8-compatible?utm_content=83823102&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

https://dmitrykornilov.net/2019/01/29/eclipse-glassfish-5-1-is-released/?utm_content=83819625&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

https://www.agilejava.eu/2019/01/29/eclipse-glassfish-5-1-is-here/?utm_content=83819640&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

http://blog.supol.cz/?p=131&utm_content=83819678&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

http://blog.supol.cz/?p=126&utm_content=83820466&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

https://www.agilejava.eu/2019/01/01/2018-annual-summary/?utm_content=83820681&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

https://waynebeaton.wordpress.com/2019/01/21/eclipse-specification-process-iv-the-specification-committee-votes/?utm_content=83820542&utm_medium=social&utm_source=twitter&hss_channel=tw-1062429085870317568

**Comment by ericpoirier** [comment]
Hi Stephanie,

These community news are now on the production website.
