### ISSUE TITLE
Update https://jakarta.ee/newsletter/ with latest Jakarta EE newsletters

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#188]
Update https://jakarta.ee/newsletter/ with https://www.eclipse.org/community/eclipse_newsletter/2018/august/  and https://www.eclipse.org/community/eclipse_newsletter/2018/november/

**Comment by ericpoirier** [comment]
Hi Stephanie,

The newsletter page on Jakarta EE is now up to date.
