### ISSUE TITLE
Please add new events

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#201]
Java EE 8 with Microprofile Bootstrap
Munich Airport, Terminal 2
April 2, 2019
http://workshops.adam-bien.com/bootstrap.htm

Effective Java EE 8 with MicroProfile
Munich Airport, Terminal 2
April 3, 2019
http://workshops.adam-bien.com/effective-javaee.htm

CD, Testing and Quality
Munich Airport, Terminal 2
April 4, 2019
http://workshops.adam-bien.com/about-testing.htm

**Comment by ericpoirier** [comment]
Hi Stephanie,

The events section is now up to date on the production website.
