### ISSUE TITLE
Please add to annoucements: https://globenewswire.com/news-release/2019/01/29/1706637/0/en/Java-EE-8-Compatible-Eclipse-GlassFish-5-1-Released.html

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#206]
Stephanie Swart <stephanie.swart@eclipse-foundation.org>

**Comment by ericpoirier** [comment]
Hi Stephanie,

I merged a pull request to add this announcement to the site. It should appear in a few minutes.
