### ISSUE TITLE
Add Jakarta EE Developer Survey

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakartaee.github.io#216]
As discussed with @stephanieswart, we would like to introduce the featured story on the front page of jakarta.ee.

We are planing to use this section to promote the new Jakarta EE Developer Survey.

We would like to replace the ad section on the right with CFA to sign up to the Jakarta EE newsletter.

Stephanie, will create a mock up with text and links.

**Comment by chrisguindon** [comment]
We are planing to update the www.eclipse.org featured story as-well with Jakarta EE Developer Survey.

@stephanieswart. will post a mock up for both on this bug.

**Comment by stephanieswart** [comment]
[jakartaee_survey_banner.zip](https://github.com/jakartaee/jakartaee.github.io/files/2927341/jakartaee_survey_banner.zip)
Here are the two banner mock-ups, one for the Jakarta EE website and the other for eclipse.org

**Comment by stephanieswart** [comment]
![rawpixel-558599-unsplash 1](https://user-images.githubusercontent.com/34580334/53748222-e757de00-3e72-11e9-8a84-c3e87faf0a14.jpg)
Here is the background image for each of those mock-ups

**Comment by ericpoirier** [comment]
Hi Stephanie,

The developer survey is now on the Jakarta EE and eclipse.org website.
