### ISSUE TITLE
Add missing testimonials on membership page

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakartaee.github.io#217]
I believe the Marketing team sent us ~10  testimonials for the https://jakarta.ee/membership/ page.

It was decided that we would initially include 3 to speed up the process of getting this page done and include the remaining one after.

Now that the page is live, we should look at writing some javascript that will display 3 testimonials at random.

https://gohugo.io/templates/data-templates/

**Comment by ericpoirier** [comment]
Hi Chris,

The missing testimonials are now on the membership page.
