### ISSUE TITLE
Please add 2 items to annoucements

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#250]
https://blogs.eclipse.org/post/wayne-beaton/renaming-java-ee-specifications-jakarta-ee

https://blogs.eclipse.org/post/tanja-obradovic/how-participate-advancing-jakarta-ee-specification-technical-and-collateral

**Comment by ericpoirier** [comment]
Hi Stephanie,

I just merged these 2 announcements on production, we should see them in a few minutes.
