### ISSUE TITLE
Please add these links to Community News

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakartaee.github.io#252]
1. https://www.agilejava.eu/2019/04/07/whats-in-a-name/
2. https://blogs.eclipse.org/post/wayne-beaton/renaming-java-ee-specifications-jakarta-ee
3. https://blogs.eclipse.org/post/tanja-obradovic/how-participate-advancing-jakarta-ee-specification-technical-and-collateral
4. https://jaxenter.com/adopting-jakarta-ee-156985.html
5. https://openliberty.io/blog/2019/03/27/integration-testing-with-testcontainers.html

Thanks!

**Comment by ltran016** [comment]
Please replace the duplicate links with these:
1. https://jaxenter.com/jakarta-ee-9-2019-outlook-156970.html
2. https://www.agilejava.eu/2019/03/18/jakarta-ee-8-status/

**Comment by ericpoirier** [comment]
Hi Laura,

The new community news items have been added to the website, they should appear in a few minutes on the web page.
