### ISSUE TITLE
Jakarta EE Newsletters

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#254]
**Is your feature request related to a problem? Please describe.**
Can you please fix the order of the Jakarta EE newsletters for the year 2018 on the https://jakarta.ee/newsletter/ page and also add 2019 year and add February newsletter https://www.eclipse.org/community/eclipse_newsletter/2019/february/ ?

.

**Comment by ericpoirier** [comment]
Hi Tanja,

I added the new newsletter and also reordered the previous ones.
