### ISSUE TITLE
Please add to Announcements: Jakarta EE at EclipseCon France 2018

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#31]
Title: Jakarta EE at EclipseCon France 2018
Copy: Meet the community at the Unconference and take in the talks on Jakarta EE, MicroServices, Microprofile and EE4J, June 11-13 in Toulouse. 
Link: https://www.eclipsecon.org/france2018/

Stephanie Swart <stephanie.swart@eclipse-foundation.org>

@chrisguindon @ericpoirier

**Comment by chrisguindon** [comment]
This was done yesterday!

Thanks!
