### ISSUE TITLE
Please add to Announcement section: https://mmilinkov.wordpress.com/2018/05/24/jakarta-ee-progress-to-date/

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#37]
https://mmilinkov.wordpress.com/2018/05/24/jakarta-ee-progress-to-date/

Stephanie Swart <stephanie.swart@eclipse-foundation.org>

@chrisguindon @ericpoirier

**Comment by chrisguindon** [comment]
This was added. Should be live any moment now!
