### ISSUE TITLE
Jakarta EE Newsletter

### ISSUE THREAD

**Issue by zestyroxy** [jakartaee/jakartaee.github.io#39]
Two things to add to the website
1) News Announcement
Title: Jakarta EE Newsletter - A First Look
Description: The first issue of the Jakarta EE quarterly newsletter has been published. Read it now!
Link: https://www.eclipse.org/community/eclipse_newsletter/2018/may/
Date: Jun 04, 2018

2) Archive list of Jakarta EE Newsletter
Issue # 1 https://www.eclipse.org/community/eclipse_newsletter/2018/may/

**Comment by chrisguindon** [comment]
Done!
