### ISSUE TITLE
Please add to community news: https://www.linuxjournal.com/content/enter-jakarta-ee-inoculation-against-fear-uncertainty-and-doubt-java-community

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#43]
Stephanie Swart <stephanie.swart@eclipse-foundation.org>

@ericpoirier @chrisguindon

**Comment by ericpoirier** [comment]
This news item has been merged in the following pull request:
https://github.com/jakartaee/jakartaee.github.io/pull/44/
