### ISSUE TITLE
Please change events to the ones below

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#54]
Javazone
Oslo Spektrum, Norway
Sep 12-Sep 13 
Link: https://2018.javazone.no/

<Keep EclipseCon Europe 2018>

W-JAX 
Munich, Germany
Nov 5-Nov 9
Link: https://jax.de/en/

Devoxx Belgium 
Antwerp, Belgium
Nov 12-Nov 16
Link: https://devoxx.be/

**Comment by ericpoirier** [comment]
The events have been updated.
