### ISSUE TITLE
Please add drop down for events section

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#69]
**Is your feature request related to a problem? Please describe.**
Yes, we need to make more space to expand our events section

**Describe the solution you'd like**
Add a drop-down button like the video section on the Eclipse Photon page

**Comment by ericpoirier** [comment]
I had to create a pull request for the Solstice Assets repo (https://github.com/EclipseFdn/solstice-assets/pull/16) to make the dropdown functionality that I used on the Photon page available to Jakarta EE and other themes.

**Comment by ericpoirier** [comment]
The dropdown is now on the production website.
