### ISSUE TITLE
Add events to event section on Jakarta EE page

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#70]
**Describe the bug**
Once the Events drop-down feature request is created, please add these events to the Jakarta EE Events section

Java @ Rio #10
Rio de Janeiro, Brazil
July 16 
Link: https://www.meetup.com/pt-BR/Java-at-Rio/events/252273260/

HackDay
Several cities in Spain / Latin América and Online
July 28
Link: https://www.youtube.com/watch?v=-LWM-xr6LP0

Oracle Developer Community LAD Tour 2018
Guatemala City, Guatemala
August 28
https://www.facebook.com/oracleguatemala/photos/a.1616743685244903.1073741830.1607759939476611/2023025271283407/?type=3&theater

**Comment by ericpoirier** [comment]
Hi Stephanie,

The more events section is now on the production website containing the new events.
