### ISSUE TITLE
Please add LifeRay logo to Participating members section of website

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#72]
[Liferay Logo Horizontal.zip](https://github.com/jakartaee/jakartaee.github.io/files/2198475/Liferay.Logo.Horizontal.zip)
Stephanie Swart <stephanie.swart@eclipse-foundation.org>

**Comment by ericpoirier** [comment]
Hi Stephanie, is this the link we should be using for this logo?
https://www.liferay.com/

If so, the logo you sent doesn't match with the logo on their website.

**Comment by ericpoirier** [comment]
A patch has been merged to add the LifeRay logo to the list of participating members.
