### ISSUE TITLE
Publishing 3 separate meeting min for Jakarta EE Steering Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#82]
**Is your feature request related to a problem? Please describe.**
This is not a problem, but we need to add 3 more entries for 
Minutes from Jakarta Steering Committee meeting of June 5
Minutes from Jakarta Steering Committee meeting of June 19
Minutes from Jakarta Steering Committee meeting of June 26
**Describe the solution you'd like**

we need to add them on 
https://jakarta.ee/meeting_minutes/

under 
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)
[Minutes from Jakarta EE Steering Committee Meeting on June 5.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2233110/Minutes.from.Jakarta.EE.Steering.Committee.Meeting.on.June.5.pdf)

**Describe alternatives you've considered**

**Additional context**
I have attached 3 pdf files. Please let me know if you need anything else from me.

[Minutes from Jakarta EE Steering Committee Meeting on June 26.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2233113/Minutes.from.Jakarta.EE.Steering.Committee.Meeting.on.June.26.pdf)
[Minutes from Jakarta EE Steering Committee Meeting on June 5.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2233114/Minutes.from.Jakarta.EE.Steering.Committee.Meeting.on.June.5.pdf)
[Minutes from Jakarta EE Steering Committee Meeting on June 19.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2233115/Minutes.from.Jakarta.EE.Steering.Committee.Meeting.on.June.19.pdf)

**Comment by ericpoirier** [comment]
Hi Tanja,

These 3 meeting minutes have been added to the production website.
