### ISSUE TITLE
Publishing meeting min for Jakarta EE Marketing Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#84]
Is your feature request related to a problem? Please describe.
This is not a problem, but we need to add an entry for Jakarta EE Marketing Committee
Jakarta EE Marketing Committee Meeting Minutes July 19.pdf

Describe the solution you'd like

we need to add them on
https://jakarta.ee/meeting_minutes/

under
Jakarta EE Marketing Committee

in the same way as other files with just adding a date with the link.
e.g, July 19, 2018 (pdf)

Describe alternatives you've considered

Additional context
I have attached the pdf file
[Jakarta EE Marketing Committee Meeting Minutes July 19.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2236348/Jakarta.EE.Marketing.Committee.Meeting.Minutes.July.19.pdf)
. Please let me know if you need anything else from me.

**Comment by ericpoirier** [comment]
Hi Tanja,

This meeting minute has been added to the production website.
