### ISSUE TITLE
Please add news item to Announcements

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#87]
### Eclipse Foundation Announces Jakarta EE Committee Election Results

**Ottawa, Canada - July 31, 2018** - Today we are pleased to announce the results of the Participant and Committer Member elections for representatives to the Jakarta EE Working Group Steering Committee, Specification Committee, and Marketing & Brand Committee. These committees provide governance for the evolution and adoption of Jakarta EE, the community-led platform created from the contribution of Java EE technologies and hosted by the Eclipse Foundation.

Congratulations to the following Committee Members: 

- Specification Committee - Participant: Alex Theedom (LJC)
- Specification Committee - Committer Member: Ivar Grimstad
- Marketing & Brand Committee - Participant: Simon Maple (LJC)
- Marketing & Brand Committee - Committer Member: Ivar Grimstad
- Steering Committee - Participant: Martijn Verburg (LJC)
- Steering Committee - Committer Member: Ivar Grimstad

We are looking forward to working with you all on the Jakarta EE Working Group committees. 
For more information about the Jakarta EE Working Group governance and processes, please visit the Jakarta EE [Working Group Charter](https://www.eclipse.org/org/workinggroups/jakarta_ee_charter.php) page. To learn more about Jakarta EE, please visit jakarta.ee.

**About the Eclipse Foundation**
The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and commercially focused environment for open source software collaboration and innovation. The Foundation is home to the Eclipse IDE, Jakarta EE, and over 350 open source projects, including runtimes, tools and frameworks for a wide range of technology domains such as IoT, automotive, geospatial, systems engineering, and many others. The Eclipse Foundation is a not-for-profit organization supported by over 275 corporate members, including industry leaders who value open source as a key enabler for business strategy. To learn more, follow us on Twitter @EclipseFdn, LinkedIn or visit eclipse.org.

**Comment by ericpoirier** [comment]
This announcement has been merged.
