### ISSUE TITLE
Please add 4 articles to community news (see links below)

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#89]
https://jaxenter.com/understanding-jakarta-ee-series-juneau-147339.html

https://jaxenter.com/understanding-jakarta-ee-series-eisele-147270.html

https://jaxenter.com/understanding-jakarta-ee-interview-keil-147483.html

https://blog.sebastian-daschner.com/entries/jakarta-ee-vision

Stephanie Swart <stephanie.swart@eclipse-foundation.org>

**Comment by ericpoirier** [comment]
Hi Stephanie,

The community news items have been added to the production website.
