### ISSUE TITLE
Publishing meeting min for Jakarta EE Marketing Committee July 26th

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#90]
Is your feature request related to a problem? Please describe.
We need to add an entry for Jakarta EE Marketing Committee
Jakarta EE Marketing Committee Meeting Minutes July 26.pdf

Describe the solution you'd like
under
Jakarta EE Marketing Committee

please publish July 26th marketing mtg min by adding a date with the link.
e.g, July 26, 2018 (pdf)

Describe alternatives you've considered

Additional context
I have attached the pdf file
Jakarta EE Marketing Committee Meeting Minutes July 26.pdf
. Please let me know if you need anything else from me.

[Jakarta EE Marketing Committee Meeting July 26.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2254657/Jakarta.EE.Marketing.Committee.Meeting.July.26.pdf)

**Comment by TanjaObradovic** [comment]
Please use this new .pdf file instead
[Jakarta EE Marketing Committee Meeting July 26 (1).pdf](https://github.com/jakartaee/jakartaee.github.io/files/2254940/Jakarta.EE.Marketing.Committee.Meeting.July.26.1.pdf)

Many thanks!

**Comment by ericpoirier** [comment]
Hi Tanja,

The new meeting minute has been added to the production website.
