### ISSUE TITLE
Publishing 4 separate meeting min for Jakarta EE Specification Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#95]
Is your feature request related to a problem? Please describe.
This is not a problem, but we need to add 4 new entries for
Minutes from Jakarta EE Specification Committee meeting of June 28
Minutes from Jakarta EE Specification Committee meeting of July 12
Minutes from Jakarta EE Specification Committee meeting of July 18
Minutes from Jakarta EE Specification Committee meeting of July 25
Describe the solution you'd like

we need to add them on
https://jakarta.ee/meeting_minutes/

under new section
Jakarta EE Specification Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)
Minutes from Jakarta EE Steering Committee Meeting on June 5.pdf

Describe alternatives you've considered

Additional context
I have attached 4 pdf files. Please let me know if you need anything else from me.
[Spec Committee meeting min July 18, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2271728/Spec.Committee.meeting.min.July.18.2018.pdf)
[Spec Committee meeting min July 25, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2271729/Spec.Committee.meeting.min.July.25.2018.pdf)
[Spec Committee meeting minutes June 28th, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2271730/Spec.Committee.meeting.minutes.June.28th.2018.pdf)
[Spec Committee meeting min July 12, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2271731/Spec.Committee.meeting.min.July.12.2018.pdf)

**Comment by ericpoirier** [comment]
Hi Tanja,

The meeting minutes from above are now available on the website.
