### ISSUE TITLE
Publishing Jakarta EE Steering Committee Meeting Minutes July 17, 2018

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#96]
Is your feature request related to a problem? Please describe.
This is not a problem, but we need to add an entry for Jakarta EE Steering 

Committee
Jakarta EE Steering Committee Meeting Minutes July 17.pdf

Describe the solution you'd like

we need to add them on
https://jakarta.ee/meeting_minutes/

under
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, July 17, 2018 (pdf)

Describe alternatives you've considered

Additional context
I have attached the pdf file
Jakarta EE Steering Committee Meeting Minutes July 17.pdf
[Minutes from Jakarta EE Steering Committee Meeting July 17, 2018.pdf](https://github.com/jakartaee/jakartaee.github.io/files/2271740/Minutes.from.Jakarta.EE.Steering.Committee.Meeting.July.17.2018.pdf)
. Please let me know if you need anything else from me.

**Comment by ericpoirier** [comment]
Hi Tanja,

This meeting minute is now available on the website.
