### ISSUE TITLE
please remove HackDay from Jakarta EE event page

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartaee.github.io#97]
please remove HackDay from Jakarta EE event page
![image](https://user-images.githubusercontent.com/34580334/43860814-e72e01e6-9b22-11e8-949e-25323670a2a0.png)

<stephanie.swart@eclipse-foundation.org>

**Comment by ericpoirier** [comment]
Hi Stephanie,

The HackDay event has been removed.
